[general]
import = [
  "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml",
]

[window]
opacity = 0.7
blur = true
startup_mode = "Maximized"
title = '快乐编程'

[scrolling]
history = 50000
multiplier = 3

[font]
size = 12
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "zellij attach --index 0 --create"] }
