[general]
import = [
  "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml",
]

[window]
opacity = 0.7
blur = true

startup_mode = "Maximized"
title = '快乐编程'

[scrolling]
history = 50000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
